### ISSUE TITLE
【依頼】ProtoSpace挙動確認	

### ISSUE THREAD

**Issue by himi513** [himi513/protospace-39810#1]
URL
https://protospace-39810.onrender.com

**Comment by shodai-ito** [comment]
@himi513 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
ユーザー詳細ページのユーザー情報が正しく表示されておりません。
<img width="768" alt="スクリーンショット 2023-09-22 17 15 17" src="https://github.com/himi513/protospace-39810/assets/62537107/c2a76317-a58a-4255-86d2-2fa85ff673b7">

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by motomuun** [comment]
@himi513 さん、再度ご提出いただきありがとうございます‼︎
動作の確認をしたところ、前回の指摘点について修正が確認できませんでした。
マージやデプロイ忘れの可能性もございます。
今一度、ご確認をお願い致します！

修正が完了しましたら、再度以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by motomuun** [comment]
@himi513 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
